export const signupForm = [
  {
    title: "First Name",
    type: "Text",
    required: true,
    outlined: false,
    dense: false,
    rounded: false,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
  {
    title: "Last Name",
    type: "Text",
    required: true,
    outlined: false,
    dense: false,
    rounded: false,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
  {
    title: "E-Mail",
    type: "E-Mail",
    required: true,
    outlined: false,
    dense: false,
    rounded: false,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
  {
    title: "Password",
    type: "Password",
    required: true,
    outlined: false,
    dense: false,
    rounded: false,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
];
export const signUp2 = [
  {
    title: "First Name",
    type: "Text",
    required: true,
    outlined: true,
    dense: false,
    rounded: true,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
  {
    title: "Last Name",
    type: "Text",
    required: true,
    outlined: true,
    dense: false,
    rounded: true,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
  {
    title: "E-Mail",
    type: "E-Mail",
    required: true,
    outlined: true,
    dense: false,
    rounded: true,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
  {
    title: "Password",
    type: "Password",
    required: true,
    outlined: true,
    dense: false,
    rounded: true,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
  {
    title: "Street Address",
    type: "Text",
    required: true,
    outlined: true,
    dense: false,
    rounded: true,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
  {
    title: "City",
    type: "Text",
    required: true,
    outlined: true,
    dense: false,
    rounded: true,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
  {
    title: "State",
    type: "Text",
    required: true,
    outlined: true,
    dense: false,
    rounded: true,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
  {
    title: "Zip code",
    type: "Number",
    required: true,
    outlined: true,
    dense: false,
    rounded: true,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
  {
    title: "Phone Number",
    type: "Number",
    required: false,
    outlined: true,
    dense: false,
    rounded: true,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
];
export const signin = [
  {
    title: "E-Mail",
    type: "E-Mail",
    required: true,
    outlined: false,
    dense: false,
    rounded: false,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
  {
    title: "Password",
    type: "Password",
    required: true,
    outlined: false,
    dense: false,
    rounded: false,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
];
export const contactUs = [
  {
    title: "First Name",
    type: "Text",
    required: true,
    outlined: true,
    dense: false,
    rounded: true,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
  {
    title: "Last Name",
    type: "Text",
    required: true,
    outlined: true,
    dense: false,
    rounded: true,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
  {
    title: "E-Mail",
    type: "E-Mail",
    required: true,
    outlined: true,
    dense: false,
    rounded: true,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
  {
    title: "Company Name",
    type: "Text",
    required: false,
    outlined: true,
    dense: false,
    rounded: true,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
  {
    title: "How did you hear about us?",
    type: "Text",
    required: false,
    outlined: true,
    dense: false,
    rounded: true,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
  {
    title: "Comments",
    type: "Text",
    required: false,
    outlined: true,
    dense: false,
    rounded: true,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
];
export const sales = [
  {
    title: "Sale Date",
    type: "Date",
    required: false,
    outlined: false,
    dense: false,
    rounded: false,
    minCurrentDay: true,
    max: 0,
    showPassOnField: false,
    value: "",
    showDatePicker: false,
  },
  {
    title: "Category",
    type: "Text",
    required: true,
    outlined: false,
    dense: false,
    rounded: false,
    minCurrentDay: false,
    max: 20,
    showPassOnField: false,
    value: "",
  },
  {
    title: "Products",
    type: "Text",
    required: true,
    outlined: false,
    dense: false,
    rounded: false,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
  {
    title: "Units Sold",
    type: "Number",
    required: true,
    outlined: false,
    dense: false,
    rounded: false,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
  {
    title: "Profit",
    type: "Number",
    required: true,
    outlined: false,
    dense: false,
    rounded: false,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
    showDollarPrefix: true,
  },
];
