export const signupForm = [
  {
    title: "Username",
    type: "Text",
    required: true,
    outlined: false,
    dense: false,
    rounded: false,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
  {
    title: "E-Mail",
    type: "E-Mail",
    required: true,
    outlined: false,
    dense: false,
    rounded: false,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
  {
    title: "Password",
    type: "Password",
    required: true,
    outlined: false,
    dense: false,
    rounded: false,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
];

export const signin = [
  {
    title: "E-Mail",
    type: "E-Mail",
    required: true,
    outlined: false,
    dense: false,
    rounded: false,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
  {
    title: "Password",
    type: "Password",
    required: true,
    outlined: false,
    dense: false,
    rounded: false,
    minCurrentDay: false,
    max: 0,
    showPassOnField: false,
    value: "",
  },
];
